### ISSUE TITLE
Support of alternate Twitter's domain names

### ISSUE THREAD

**Issue by ReiFan49** [TaYaKi71751/set-twitter-logo#2]
I see that `pbs.twimg.com` (Twitter's media) domain had its favicon also turned into that thing, does this extension able to provide such support to include this, and possibly any other Twitter's owned unmentioned domains out there?

**Comment by TaYaKi71751** [comment]
`content-security-policy` header from 
https://x.com/${USER_ID}/status/${TWEET_ID}

**Comment by TaYaKi71751** [comment]
![image](https://github.com/TaYaKi71751/set-twitter-logo/assets/56256195/66bdc08f-03f7-40ac-8147-a7ae158dfedd)

**Comment by TaYaKi71751** [comment]
https://github.com/TaYaKi71751/set-twitter-logo/commit/2b5e175c1a81d0e3857f0f041def33414729ec59

**Comment by TaYaKi71751** [comment]
https://github.com/TaYaKi71751/set-twitter-logo/commit/e47cc15f0ee85dfe1a4544595dd2476673d910c7

**Comment by TaYaKi71751** [comment]
![image](https://github.com/TaYaKi71751/set-twitter-logo/assets/56256195/5a64e556-7827-48ed-bc5d-a7ef3f62977e)

**Comment by TaYaKi71751** [comment]
ffe0182ea0050848be5b3e24d9f8dee66a389344
ed8380f35c64772014a5e61b9ae972582714c575

**Comment by TaYaKi71751** [comment]
![image](https://github.com/TaYaKi71751/set-twitter-logo/assets/56256195/8ba70890-bb6b-45a8-a24e-f15aca7ef7b9)
1.0.11 has been approved

**Comment by TaYaKi71751** [comment]
with *.twimg.com

**Comment by TaYaKi71751** [comment]
Check the update of extension via https://addons.mozilla.org/en-US/firefox/addon/change-twitter-logo-back/
